import "../.."
import QtQuick

Column {
    id: weatherSection

    property var host
    property var settings: Settings

    visible: host && host.currentOtherTab === 3
    width: parent ? parent.width : 0
    spacing: 10

                Text {
                    visible: host.currentOtherTab === 3 && host.currentOtherSubTab === 0
                    text: "Токен Gismeteo"
                    color: Config.text
                    font.family: Config.settingsFont
                    font.pixelSize: Config.settingsUiSize(13)
                }
                SettingsTextField {
                    visible: host.currentOtherTab === 3 && host.currentOtherSubTab === 0
                    id: token
                    width: parent.width
                    height: 34
                    text: settings.weatherToken
                    color: Config.text
                    selectionColor: Config.accent
                    selectedTextColor: Config.black
                    placeholderText: "Введите токен Gismeteo"
                    placeholderTextColor: Config.textMuted
                    font.family: Config.settingsFont
                    font.pixelSize: Config.settingsUiSize(12)
                    activeFocusOnTab: true
                    background: Rectangle {
                        color: Config.settingsBackground
                        border.color: (token.activeFocus || token.pointerHovered) ? Config.accent : Config.baseColor
                        border.width: 1
                        radius: Config.radius
                    }
                    onEditingFinished: {
                        settings.weatherToken = text
                        settings.save()
                    }
                }
                Row { width: parent.width; height: 30; spacing: 8
                    visible: host.currentOtherTab === 3 && host.currentOtherSubTab === 0
                    Text { width: 210; text: "Погода сейчас (мин)"; color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); verticalAlignment: Text.AlignVCenter }
                    SettingsTextField { id: weatherNowIntervalField; width: 100; height: 30; text: String(Config.weatherNowIntervalMinutes); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; background: Rectangle {
                        color: Config.settingsBackground; border.color: (parent.activeFocus || parent.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 }
                        function applyValue() { var n=Number(text); if(!isFinite(n)) n=Config.weatherNowIntervalMinutes; n=Math.max(1,Math.min(1440,Math.round(n))); Config.weatherNowIntervalMinutes=n; text=String(n); settings.save() }
                        onEditingFinished: applyValue(); MouseArea { anchors.fill: parent; acceptedButtons: Qt.NoButton; onWheel: wheel=>{ var n=Math.max(1,Math.min(1440,Config.weatherNowIntervalMinutes+host.wheelDelta(wheel, 1))); Config.weatherNowIntervalMinutes=n; text=String(n); settings.save(); wheel.accepted=true } }
                    }
                }
                Row { width: parent.width; height: 30; spacing: 8
                    visible: host.currentOtherTab === 3 && host.currentOtherSubTab === 0
                    Text { width: 210; text: "Погода по часам (мин)"; color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); verticalAlignment: Text.AlignVCenter }
                    SettingsTextField { id: weatherHourlyIntervalField; width: 100; height: 30; text: String(Config.weatherHourlyIntervalMinutes); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; background: Rectangle {
                        color: Config.settingsBackground; border.color: (parent.activeFocus || parent.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 }
                        function applyValue() { var n=Number(text); if(!isFinite(n)) n=Config.weatherHourlyIntervalMinutes; n=Math.max(1,Math.min(1440,Math.round(n))); Config.weatherHourlyIntervalMinutes=n; text=String(n); settings.save() }
                        onEditingFinished: applyValue(); MouseArea { anchors.fill: parent; acceptedButtons: Qt.NoButton; onWheel: wheel=>{ var n=Math.max(1,Math.min(1440,Config.weatherHourlyIntervalMinutes+host.wheelDelta(wheel, 1))); Config.weatherHourlyIntervalMinutes=n; text=String(n); settings.save(); wheel.accepted=true } }
                    }
                }
                Row { width: parent.width; height: 30; spacing: 8
                    visible: host.currentOtherTab === 3 && host.currentOtherSubTab === 0
                    Text { width: 210; text: "Погода по дням (мин)"; color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); verticalAlignment: Text.AlignVCenter }
                    SettingsTextField { id: weatherDailyIntervalField; width: 100; height: 30; text: String(Config.weatherDailyIntervalMinutes); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; background: Rectangle {
                        color: Config.settingsBackground; border.color: (parent.activeFocus || parent.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 }
                        function applyValue() { var n=Number(text); if(!isFinite(n)) n=Config.weatherDailyIntervalMinutes; n=Math.max(1,Math.min(1440,Math.round(n))); Config.weatherDailyIntervalMinutes=n; text=String(n); settings.save() }
                        onEditingFinished: applyValue(); MouseArea { anchors.fill: parent; acceptedButtons: Qt.NoButton; onWheel: wheel=>{ var n=Math.max(1,Math.min(1440,Config.weatherDailyIntervalMinutes+host.wheelDelta(wheel, 1))); Config.weatherDailyIntervalMinutes=n; text=String(n); settings.save(); wheel.accepted=true } }
                    }
                }
                Row { width: parent.width; height: 30; spacing: 8
                    visible: host.currentOtherTab === 3 && host.currentOtherSubTab === 0
                    Text { width: 210; text: "Повтор после ошибки (мин)"; color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); verticalAlignment: Text.AlignVCenter; elide: Text.ElideRight }
                    SettingsTextField { id: weatherRetryDelayField; width: 100; height: 30; text: String(Config.weatherRetryDelayMinutes); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; background: Rectangle {
                        color: Config.settingsBackground; border.color: (parent.activeFocus || parent.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 }
                        function applyValue() { var n=Number(text); if(!isFinite(n)) n=Config.weatherRetryDelayMinutes; n=Math.max(1,Math.min(1440,Math.round(n))); Config.weatherRetryDelayMinutes=n; text=String(n); settings.save() }
                        onEditingFinished: applyValue(); MouseArea { anchors.fill: parent; acceptedButtons: Qt.NoButton; onWheel: wheel=>{ var n=Math.max(1,Math.min(1440,Config.weatherRetryDelayMinutes+host.wheelDelta(wheel, 1))); Config.weatherRetryDelayMinutes=n; text=String(n); settings.save(); wheel.accepted=true } }
                    }
                }
                Row { width: parent.width; height: 30; spacing: 8
                    visible: host.currentOtherTab === 3 && host.currentOtherSubTab === 0
                    Text { width: 210; text: "Пауза между ручными обновлениями (с)"; color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); verticalAlignment: Text.AlignVCenter; elide: Text.ElideRight }
                    SettingsTextField { id: weatherManualCooldownField; width: 100; height: 30; text: String(Config.weatherManualRefreshCooldownSeconds); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; background: Rectangle {
                        color: Config.settingsBackground; border.color: (parent.activeFocus || parent.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 }
                        function applyValue() { var n=Number(text); if(!isFinite(n)) n=Config.weatherManualRefreshCooldownSeconds; n=Math.max(5,Math.min(3600,Math.round(n))); Config.weatherManualRefreshCooldownSeconds=n; text=String(n); settings.save() }
                        onEditingFinished: applyValue(); MouseArea { anchors.fill: parent; acceptedButtons: Qt.NoButton; onWheel: wheel=>{ var n=Math.max(5,Math.min(3600,Config.weatherManualRefreshCooldownSeconds+host.wheelDelta(wheel, 1))); Config.weatherManualRefreshCooldownSeconds=n; text=String(n); settings.save(); wheel.accepted=true } }
                    }
                }
                Text { visible: host.currentOtherTab === 3 && host.currentOtherSubTab === 1; text: "Иконка текущей погоды"; color: Config.settingsSubheading; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(10) }
                Row { visible: host.currentOtherTab === 3 && host.currentOtherSubTab === 1; width: parent.width; height: 24; spacing: 8
                    Item { width: 210; height: 24 }
                    Text { width: 58; text: "Y"; color: Config.textMuted; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(10); horizontalAlignment: Text.AlignHCenter; verticalAlignment: Text.AlignVCenter }
                    Text { width: 58; text: "Размер"; color: Config.textMuted; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(10); horizontalAlignment: Text.AlignHCenter; verticalAlignment: Text.AlignVCenter }
                }
                Row { visible: host.currentOtherTab === 3 && host.currentOtherSubTab === 1; width: parent.width; height: 30; spacing: 8
                    Text { width: 210; text: "Иконка ветра"; color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); verticalAlignment: Text.AlignVCenter }
                    SettingsTextField { id: weatherWindIconField; width: 160; height: 30; text: Config.weatherWindIcon; color: Config.text; selectionColor: Config.accent; selectedTextColor: Config.black; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(12); activeFocusOnTab: true; background: Rectangle { color: Config.settingsBackground; border.color: (weatherWindIconField.activeFocus || weatherWindIconField.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 }
                        onEditingFinished: { Config.weatherWindIcon = text; text = Config.weatherWindIcon; settings.save() }
                        Connections { target: Config; function onWeatherWindIconChanged() { weatherWindIconField.text = Config.weatherWindIcon } }
                    }
                }
                Row { width: parent.width; height: 30; spacing: 8
                    visible: host.currentOtherTab === 3 && host.currentOtherSubTab === 1
                    Text { width: 210; text: "Размер иконки текущей погоды"; color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); verticalAlignment: Text.AlignVCenter; elide: Text.ElideRight }
                    SettingsTextField { id: weatherIconSizeField; width: 100; height: 30; text: String(Config.weatherIconSize); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; background: Rectangle {
                        color: Config.settingsBackground; border.color: (parent.activeFocus || parent.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 }
                        function applyValue(v) { var n=Number(v); if(!isFinite(n)) n=Config.weatherIconSize; n=Math.max(16,Math.min(128,Math.round(n / 1) * 1)); Config.weatherIconSize=n; text=String(n); settings.save() }
                        onEditingFinished: applyValue(text); MouseArea { anchors.fill: parent; acceptedButtons: Qt.NoButton; onWheel: wheel=>{ weatherIconSizeField.applyValue(Config.weatherIconSize+host.wheelDelta(wheel, 1)); wheel.accepted=true } }
                    }
                }
                Row { width: parent.width; height: 30; spacing: 8
                    visible: host.currentOtherTab === 3 && host.currentOtherSubTab === 1
                    Text { width: 210; text: "Размер стрелки ветра"; color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); verticalAlignment: Text.AlignVCenter; elide: Text.ElideRight }
                    SettingsTextField { id: weatherArrowSizeField; width: 100; height: 30; text: String(Config.weatherArrowSize); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; background: Rectangle {
                        color: Config.settingsBackground; border.color: (parent.activeFocus || parent.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 }
                        function applyValue(v) { var n=Number(v); if(!isFinite(n)) n=Config.weatherArrowSize; n=Math.max(8,Math.min(64,Math.round(n / 1) * 1)); Config.weatherArrowSize=n; text=String(n); settings.save() }
                        onEditingFinished: applyValue(text); MouseArea { anchors.fill: parent; acceptedButtons: Qt.NoButton; onWheel: wheel=>{ weatherArrowSizeField.applyValue(Config.weatherArrowSize+host.wheelDelta(wheel, 1)); wheel.accepted=true } }
                    }
                }
                Row { width: parent.width; height: 30; spacing: 8
                    visible: host.currentOtherTab === 3 && host.currentOtherSubTab === 1
                    Text { width: 210; text: "Смещение стрелки ветра по Y"; color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); verticalAlignment: Text.AlignVCenter; elide: Text.ElideRight }
                    SettingsTextField { id: weatherArrowYField; width: 100; height: 30; text: String(Config.weatherArrowYOffset); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; background: Rectangle {
                        color: Config.settingsBackground; border.color: (parent.activeFocus || parent.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 }
                        function applyValue(v) { var n=Number(v); if(!isFinite(n)) n=Config.weatherArrowYOffset; n=Math.max(-40,Math.min(40,Math.round(n / 1) * 1)); Config.weatherArrowYOffset=n; text=String(n); settings.save() }
                        onEditingFinished: applyValue(text); MouseArea { anchors.fill: parent; acceptedButtons: Qt.NoButton; onWheel: wheel=>{ weatherArrowYField.applyValue(Config.weatherArrowYOffset+host.wheelDelta(wheel, 1)); wheel.accepted=true } }
                    }
                }
                Row { width: parent.width; height: 30; spacing: 8
                    visible: host.currentOtherTab === 3 && host.currentOtherSubTab === 1
                    Text { width: 210; text: "Зазор стрелки до скорости"; color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); verticalAlignment: Text.AlignVCenter; elide: Text.ElideRight }
                    SettingsTextField { id: weatherWindGapField; width: 100; height: 30; text: String(Config.weatherWindArrowGap); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; background: Rectangle {
                        color: Config.settingsBackground; border.color: (parent.activeFocus || parent.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 }
                        function applyValue(v) { var n=Number(v); if(!isFinite(n)) n=Config.weatherWindArrowGap; n=Math.max(-20,Math.min(40,Math.round(n / 1) * 1)); Config.weatherWindArrowGap=n; text=String(n); settings.save() }
                        onEditingFinished: applyValue(text); MouseArea { anchors.fill: parent; acceptedButtons: Qt.NoButton; onWheel: wheel=>{ weatherWindGapField.applyValue(Config.weatherWindArrowGap+host.wheelDelta(wheel, 1)); wheel.accepted=true } }
                    }
                }
                Text {
                    visible: host.currentOtherTab === 3 && host.currentOtherSubTab === 1
                    text: "Дополнительная геометрия текущей погоды"
                    color: Config.settingsSubheading
                    font.family: Config.settingsFont
                    font.pixelSize: Config.settingsUiSize(10)
                }
                Row { visible: host.currentOtherTab === 3 && host.currentOtherSubTab === 1; width: parent.width; height: 30; spacing: 8
                    Text { width: 210; text: "Y картинки текущей погоды"; color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); verticalAlignment: Text.AlignVCenter }
                    SettingsTextField { id: weatherIconYField; width: 100; height: 30; text: String(Config.weatherIconY); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; inputMethodHints: Qt.ImhNone; background: Rectangle { color: Config.settingsBackground; border.color: (weatherIconYField.activeFocus || weatherIconYField.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 }
                        function applyValue(v){var n=Number(v);if(!isFinite(n))n=Config.weatherIconY;n=Math.max(-100,Math.min(100,Math.round(n)));Config.weatherIconY=n;text=String(n);settings.save()}
                        onEditingFinished:applyValue(text);MouseArea{anchors.fill:parent;acceptedButtons:Qt.NoButton;onWheel:wheel=>{weatherIconYField.applyValue(Config.weatherIconY+host.wheelDelta(wheel, 1));wheel.accepted=true}} Connections{target:Config;function onWeatherIconYChanged(){weatherIconYField.text=String(Config.weatherIconY)}}
                    }
                }
                Row { visible: host.currentOtherTab === 3 && host.currentOtherSubTab === 1; width: parent.width; height: 30; spacing: 8
                    Text { width: 210; text: "X колонки ветра"; color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); verticalAlignment: Text.AlignVCenter }
                    SettingsTextField { id: weatherWindXField; width: 100; height: 30; text: String(Config.weatherWindColumnX); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; inputMethodHints: Qt.ImhDigitsOnly; background: Rectangle { color: Config.settingsBackground; border.color: (weatherWindXField.activeFocus || weatherWindXField.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 }
                        function applyValue(v){var n=Number(v);if(!isFinite(n))n=Config.weatherWindColumnX;n=Math.max(0,Math.min(500,Math.round(n)));Config.weatherWindColumnX=n;text=String(n);settings.save()}
                        onEditingFinished:applyValue(text);MouseArea{anchors.fill:parent;acceptedButtons:Qt.NoButton;onWheel:wheel=>{weatherWindXField.applyValue(Config.weatherWindColumnX+host.wheelDelta(wheel, 1));wheel.accepted=true}} Connections{target:Config;function onWeatherWindColumnXChanged(){weatherWindXField.text=String(Config.weatherWindColumnX)}}
                    }
                }
                Row { visible: host.currentOtherTab === 3 && host.currentOtherSubTab === 1; width: parent.width; height: 30; spacing: 8
                    Text { width: 210; text: "Размер текста описания"; color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); verticalAlignment: Text.AlignVCenter }
                    SettingsTextField { id: weatherDescSizeField; width: 100; height: 30; text: String(Config.weatherDescriptionFontSize); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; inputMethodHints: Qt.ImhDigitsOnly; background: Rectangle { color: Config.settingsBackground; border.color: (weatherDescSizeField.activeFocus || weatherDescSizeField.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 }
                        function applyValue(v){var n=Number(v);if(!isFinite(n))n=Config.weatherDescriptionFontSize;n=Math.max(6,Math.min(48,Math.round(n)));Config.weatherDescriptionFontSize=n;text=String(n);settings.save()}
                        onEditingFinished:applyValue(text);MouseArea{anchors.fill:parent;acceptedButtons:Qt.NoButton;onWheel:wheel=>{weatherDescSizeField.applyValue(Config.weatherDescriptionFontSize+host.wheelDelta(wheel, 1));wheel.accepted=true}} Connections{target:Config;function onWeatherDescriptionFontSizeChanged(){weatherDescSizeField.text=String(Config.weatherDescriptionFontSize)}}
                    }
                }
                Text { visible: host.currentOtherTab === 3 && host.currentOtherSubTab === 1; text: "Дополнительная геометрия и типографика"; color: Config.settingsSubheading; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(10) }
                Row { visible: host.currentOtherTab === 3 && host.currentOtherSubTab === 1; width: parent.width; height: 30; spacing: 8
                    Text { width: 210; text: "Температура: ширина колонки"; color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); verticalAlignment: Text.AlignVCenter }
                    SettingsTextField { id: weatherTempColumnWidthField; width: 100; height: 30; text: String(Config.weatherTempColumnWidth); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; inputMethodHints: Qt.ImhDigitsOnly; background: Rectangle { color: Config.settingsBackground; border.color: (weatherTempColumnWidthField.activeFocus || weatherTempColumnWidthField.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 }
                        function applyValue(v){var n=Number(v);if(!isFinite(n))n=Config.weatherTempColumnWidth;n=Math.max(40,Math.min(200,Math.round(n)));Config.weatherTempColumnWidth=n;text=String(n);settings.save()}
                        onEditingFinished:applyValue(text);MouseArea{anchors.fill:parent;acceptedButtons:Qt.NoButton;onWheel:wheel=>{weatherTempColumnWidthField.applyValue(Config.weatherTempColumnWidth+host.wheelDelta(wheel, 1));wheel.accepted=true}} Connections{target:Config;function onWeatherTempColumnWidthChanged(){weatherTempColumnWidthField.text=String(Config.weatherTempColumnWidth)}}
                    }
                }
                Row { visible: host.currentOtherTab === 3 && host.currentOtherSubTab === 1; width: parent.width; height: 30; spacing: 8
                    Text { width: 210; text: "Температура: X / ширина"; color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); verticalAlignment: Text.AlignVCenter }
                    SettingsTextField { id: weatherTempXField; width: 70; height: 30; text: String(Config.weatherTempX); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; inputMethodHints: Qt.ImhDigitsOnly; background: Rectangle { color: Config.settingsBackground; border.color: (weatherTempXField.activeFocus || weatherTempXField.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 }
                        function applyValue(v){var n=Number(v);if(!isFinite(n))n=Config.weatherTempX;n=Math.max(0,Math.min(200,Math.round(n)));Config.weatherTempX=n;text=String(n);settings.save()}
                        onEditingFinished:applyValue(text);MouseArea{anchors.fill:parent;acceptedButtons:Qt.NoButton;onWheel:wheel=>{weatherTempXField.applyValue(Config.weatherTempX+host.wheelDelta(wheel, 1));wheel.accepted=true}} Connections{target:Config;function onWeatherTempXChanged(){weatherTempXField.text=String(Config.weatherTempX)}}
                    }
                    SettingsTextField { id: weatherTempWidthField; width: 70; height: 30; text: String(Config.weatherTempWidth); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; inputMethodHints: Qt.ImhDigitsOnly; background: Rectangle { color: Config.settingsBackground; border.color: (weatherTempWidthField.activeFocus || weatherTempWidthField.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 }
                        function applyValue(v){var n=Number(v);if(!isFinite(n))n=Config.weatherTempWidth;n=Math.max(20,Math.min(200,Math.round(n)));Config.weatherTempWidth=n;text=String(n);settings.save()}
                        onEditingFinished:applyValue(text);MouseArea{anchors.fill:parent;acceptedButtons:Qt.NoButton;onWheel:wheel=>{weatherTempWidthField.applyValue(Config.weatherTempWidth+host.wheelDelta(wheel, 1));wheel.accepted=true}} Connections{target:Config;function onWeatherTempWidthChanged(){weatherTempWidthField.text=String(Config.weatherTempWidth)}}
                    }
                }
                Row { visible: host.currentOtherTab === 3 && host.currentOtherSubTab === 1; width: parent.width; height: 30; spacing: 8
                    Text { width: 210; text: "Комфорт: Y"; color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); verticalAlignment: Text.AlignVCenter }
                    SettingsTextField { id: weatherComfortYField; width: 70; height: 30; text: String(Config.weatherComfortY); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; inputMethodHints: Qt.ImhNone; background: Rectangle { color: Config.settingsBackground; border.color: (weatherComfortYField.activeFocus || weatherComfortYField.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 }
                        function applyValue(v){var n=Number(v);if(!isFinite(n))n=Config.weatherComfortY;n=Math.max(-20,Math.min(100,Math.round(n)));Config.weatherComfortY=n;text=String(n);settings.save()}
                        onEditingFinished:applyValue(text);MouseArea{anchors.fill:parent;acceptedButtons:Qt.NoButton;onWheel:wheel=>{weatherComfortYField.applyValue(Config.weatherComfortY+host.wheelDelta(wheel, 1));wheel.accepted=true}} Connections{target:Config;function onWeatherComfortYChanged(){weatherComfortYField.text=String(Config.weatherComfortY)}}
                    }
                }
                Row { visible: host.currentOtherTab === 3 && host.currentOtherSubTab === 1; width: parent.width; height: 30; spacing: 8
                    Text { width: 210; text: "Основная температура: отступ X / Y"; color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); verticalAlignment: Text.AlignVCenter }
                    SettingsTextField { id: weatherTempOffsetXField; width: 70; height: 30; text: String(Config.weatherTempOffsetX); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; inputMethodHints: Qt.ImhNone; background: Rectangle { color: Config.settingsBackground; border.color: (weatherTempOffsetXField.activeFocus || weatherTempOffsetXField.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 }
                        function applyValue(v){var n=Number(v);if(!isFinite(n))n=Config.weatherTempOffsetX;n=Math.max(-100,Math.min(100,Math.round(n)));Config.weatherTempOffsetX=n;text=String(n);settings.save()}
                        onEditingFinished:applyValue(text);MouseArea{anchors.fill:parent;acceptedButtons:Qt.NoButton;onWheel:wheel=>{weatherTempOffsetXField.applyValue(Config.weatherTempOffsetX+host.wheelDelta(wheel, 1));wheel.accepted=true}} Connections{target:Config;function onWeatherTempOffsetXChanged(){weatherTempOffsetXField.text=String(Config.weatherTempOffsetX)}}
                    }
                    SettingsTextField { id: weatherTempOffsetYField; width: 70; height: 30; text: String(Config.weatherTempOffsetY); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; inputMethodHints: Qt.ImhNone; background: Rectangle { color: Config.settingsBackground; border.color: (weatherTempOffsetYField.activeFocus || weatherTempOffsetYField.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 }
                        function applyValue(v){var n=Number(v);if(!isFinite(n))n=Config.weatherTempOffsetY;n=Math.max(-100,Math.min(100,Math.round(n)));Config.weatherTempOffsetY=n;text=String(n);settings.save()}
                        onEditingFinished:applyValue(text);MouseArea{anchors.fill:parent;acceptedButtons:Qt.NoButton;onWheel:wheel=>{weatherTempOffsetYField.applyValue(Config.weatherTempOffsetY+host.wheelDelta(wheel, 1));wheel.accepted=true}} Connections{target:Config;function onWeatherTempOffsetYChanged(){weatherTempOffsetYField.text=String(Config.weatherTempOffsetY)}}
                    }
                }
                Row { visible: host.currentOtherTab === 3 && host.currentOtherSubTab === 1; width: parent.width; height: 30; spacing: 8
                    Text { width: 210; text: "Температура комфорта: отступ X / Y"; color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); verticalAlignment: Text.AlignVCenter }
                    SettingsTextField { id: weatherComfortOffsetXField; width: 70; height: 30; text: String(Config.weatherComfortOffsetX); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; inputMethodHints: Qt.ImhNone; background: Rectangle { color: Config.settingsBackground; border.color: (weatherComfortOffsetXField.activeFocus || weatherComfortOffsetXField.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 }
                        function applyValue(v){var n=Number(v);if(!isFinite(n))n=Config.weatherComfortOffsetX;n=Math.max(-100,Math.min(100,Math.round(n)));Config.weatherComfortOffsetX=n;text=String(n);settings.save()}
                        onEditingFinished:applyValue(text);MouseArea{anchors.fill:parent;acceptedButtons:Qt.NoButton;onWheel:wheel=>{weatherComfortOffsetXField.applyValue(Config.weatherComfortOffsetX+host.wheelDelta(wheel, 1));wheel.accepted=true}} Connections{target:Config;function onWeatherComfortOffsetXChanged(){weatherComfortOffsetXField.text=String(Config.weatherComfortOffsetX)}}
                    }
                    SettingsTextField { id: weatherComfortOffsetYField; width: 70; height: 30; text: String(Config.weatherComfortOffsetY); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; inputMethodHints: Qt.ImhNone; background: Rectangle { color: Config.settingsBackground; border.color: (weatherComfortOffsetYField.activeFocus || weatherComfortOffsetYField.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 }
                        function applyValue(v){var n=Number(v);if(!isFinite(n))n=Config.weatherComfortOffsetY;n=Math.max(-100,Math.min(100,Math.round(n)));Config.weatherComfortOffsetY=n;text=String(n);settings.save()}
                        onEditingFinished:applyValue(text);MouseArea{anchors.fill:parent;acceptedButtons:Qt.NoButton;onWheel:wheel=>{weatherComfortOffsetYField.applyValue(Config.weatherComfortOffsetY+host.wheelDelta(wheel, 1));wheel.accepted=true}} Connections{target:Config;function onWeatherComfortOffsetYChanged(){weatherComfortOffsetYField.text=String(Config.weatherComfortOffsetY)}}
                    }
                }
                Row { visible: host.currentOtherTab === 3 && host.currentOtherSubTab === 1; width: parent.width; height: 30; spacing: 8
                    Text { width: 210; text: "Ветер: X / ширина"; color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); verticalAlignment: Text.AlignVCenter }
                    SettingsTextField { id: weatherWindColumnXExtraField; width: 70; height: 30; text: String(Config.weatherWindColumnX); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; inputMethodHints: Qt.ImhDigitsOnly; background: Rectangle { color: Config.settingsBackground; border.color: (weatherWindColumnXExtraField.activeFocus || weatherWindColumnXExtraField.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 }
                        function applyValue(v){var n=Number(v);if(!isFinite(n))n=Config.weatherWindColumnX;n=Math.max(0,Math.min(500,Math.round(n)));Config.weatherWindColumnX=n;text=String(n);settings.save()}
                        onEditingFinished:applyValue(text);MouseArea{anchors.fill:parent;acceptedButtons:Qt.NoButton;onWheel:wheel=>{weatherWindColumnXExtraField.applyValue(Config.weatherWindColumnX+host.wheelDelta(wheel, 1));wheel.accepted=true}} Connections{target:Config;function onWeatherWindColumnXChanged(){weatherWindColumnXExtraField.text=String(Config.weatherWindColumnX)}}
                    }
                    SettingsTextField { id: weatherWindColumnWidthExtraField; width: 70; height: 30; text: String(Config.weatherWindColumnWidth); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; inputMethodHints: Qt.ImhDigitsOnly; background: Rectangle { color: Config.settingsBackground; border.color: (weatherWindColumnWidthExtraField.activeFocus || weatherWindColumnWidthExtraField.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 }
                        function applyValue(v){var n=Number(v);if(!isFinite(n))n=Config.weatherWindColumnWidth;n=Math.max(60,Math.min(300,Math.round(n)));Config.weatherWindColumnWidth=n;text=String(n);settings.save()}
                        onEditingFinished:applyValue(text);MouseArea{anchors.fill:parent;acceptedButtons:Qt.NoButton;onWheel:wheel=>{weatherWindColumnWidthExtraField.applyValue(Config.weatherWindColumnWidth+host.wheelDelta(wheel, 1));wheel.accepted=true}} Connections{target:Config;function onWeatherWindColumnWidthChanged(){weatherWindColumnWidthExtraField.text=String(Config.weatherWindColumnWidth)}}
                    }
                }
                Row { visible: host.currentOtherTab === 3 && host.currentOtherSubTab === 1; width: parent.width; height: 30; spacing: 8
                    Text { width: 210; text: "Стрелка: ширина / высота"; color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); verticalAlignment: Text.AlignVCenter }
                    SettingsTextField { id: weatherWindArrowWidthField; width: 70; height: 30; text: String(Config.weatherWindArrowWidth); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; inputMethodHints: Qt.ImhDigitsOnly; background: Rectangle { color: Config.settingsBackground; border.color: (weatherWindArrowWidthField.activeFocus || weatherWindArrowWidthField.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 }
                        function applyValue(v){var n=Number(v);if(!isFinite(n))n=Config.weatherWindArrowWidth;n=Math.max(8,Math.min(50,Math.round(n)));Config.weatherWindArrowWidth=n;text=String(n);settings.save()}
                        onEditingFinished:applyValue(text);MouseArea{anchors.fill:parent;acceptedButtons:Qt.NoButton;onWheel:wheel=>{weatherWindArrowWidthField.applyValue(Config.weatherWindArrowWidth+host.wheelDelta(wheel, 1));wheel.accepted=true}} Connections{target:Config;function onWeatherWindArrowWidthChanged(){weatherWindArrowWidthField.text=String(Config.weatherWindArrowWidth)}}
                    }
                    SettingsTextField { id: weatherWindArrowHeightField; width: 70; height: 30; text: String(Config.weatherWindArrowHeight); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; inputMethodHints: Qt.ImhDigitsOnly; background: Rectangle { color: Config.settingsBackground; border.color: (weatherWindArrowHeightField.activeFocus || weatherWindArrowHeightField.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 }
                        function applyValue(v){var n=Number(v);if(!isFinite(n))n=Config.weatherWindArrowHeight;n=Math.max(15,Math.min(80,Math.round(n)));Config.weatherWindArrowHeight=n;text=String(n);settings.save()}
                        onEditingFinished:applyValue(text);MouseArea{anchors.fill:parent;acceptedButtons:Qt.NoButton;onWheel:wheel=>{weatherWindArrowHeightField.applyValue(Config.weatherWindArrowHeight+host.wheelDelta(wheel, 1));wheel.accepted=true}} Connections{target:Config;function onWeatherWindArrowHeightChanged(){weatherWindArrowHeightField.text=String(Config.weatherWindArrowHeight)}}
                    }
                }
                Row { visible: host.currentOtherTab === 3 && host.currentOtherSubTab === 1; width: parent.width; height: 30; spacing: 8
                    Text { width: 210; text: "Скорость ветра: X / Y / ширина"; color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); verticalAlignment: Text.AlignVCenter }
                    SettingsTextField { id: weatherWindSpeedXExtraField; width: 62; height: 30; text: String(Config.weatherWindSpeedX); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; inputMethodHints: Qt.ImhDigitsOnly; background: Rectangle { color: Config.settingsBackground; border.color: (weatherWindSpeedXExtraField.activeFocus || weatherWindSpeedXExtraField.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 }
                        function applyValue(v){var n=Number(v);if(!isFinite(n))n=Config.weatherWindSpeedX;n=Math.max(0,Math.min(250,Math.round(n)));Config.weatherWindSpeedX=n;text=String(n);settings.save()}
                        onEditingFinished:applyValue(text);MouseArea{anchors.fill:parent;acceptedButtons:Qt.NoButton;onWheel:wheel=>{weatherWindSpeedXExtraField.applyValue(Config.weatherWindSpeedX+host.wheelDelta(wheel, 1));wheel.accepted=true}} Connections{target:Config;function onWeatherWindSpeedXChanged(){weatherWindSpeedXExtraField.text=String(Config.weatherWindSpeedX)}}
                    }
                    SettingsTextField { id: weatherWindSpeedYExtraField; width: 62; height: 30; text: String(Config.weatherWindSpeedY); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; inputMethodHints: Qt.ImhNone; background: Rectangle { color: Config.settingsBackground; border.color: (weatherWindSpeedYExtraField.activeFocus || weatherWindSpeedYExtraField.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 }
                        function applyValue(v){var n=Number(v);if(!isFinite(n))n=Config.weatherWindSpeedY;n=Math.max(-20,Math.min(80,Math.round(n)));Config.weatherWindSpeedY=n;text=String(n);settings.save()}
                        onEditingFinished:applyValue(text);MouseArea{anchors.fill:parent;acceptedButtons:Qt.NoButton;onWheel:wheel=>{weatherWindSpeedYExtraField.applyValue(Config.weatherWindSpeedY+host.wheelDelta(wheel, 1));wheel.accepted=true}} Connections{target:Config;function onWeatherWindSpeedYChanged(){weatherWindSpeedYExtraField.text=String(Config.weatherWindSpeedY)}}
                    }
                    SettingsTextField { id: weatherWindSpeedWidthExtraField; width: 62; height: 30; text: String(Config.weatherWindSpeedWidth); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; inputMethodHints: Qt.ImhDigitsOnly; background: Rectangle { color: Config.settingsBackground; border.color: (weatherWindSpeedWidthExtraField.activeFocus || weatherWindSpeedWidthExtraField.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 }
                        function applyValue(v){var n=Number(v);if(!isFinite(n))n=Config.weatherWindSpeedWidth;n=Math.max(20,Math.min(150,Math.round(n)));Config.weatherWindSpeedWidth=n;text=String(n);settings.save()}
                        onEditingFinished:applyValue(text);MouseArea{anchors.fill:parent;acceptedButtons:Qt.NoButton;onWheel:wheel=>{weatherWindSpeedWidthExtraField.applyValue(Config.weatherWindSpeedWidth+host.wheelDelta(wheel, 1));wheel.accepted=true}} Connections{target:Config;function onWeatherWindSpeedWidthChanged(){weatherWindSpeedWidthExtraField.text=String(Config.weatherWindSpeedWidth)}}
                    }
                }
                Row { visible: host.currentOtherTab === 3 && host.currentOtherSubTab === 1; width: parent.width; height: 30; spacing: 8
                    Text { width: 210; text: "Ед. ветра: X / Y / ширина"; color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); verticalAlignment: Text.AlignVCenter }
                    SettingsTextField { id: weatherWindUnitXExtraField; width: 62; height: 30; text: String(Config.weatherWindUnitX); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; inputMethodHints: Qt.ImhDigitsOnly; background: Rectangle { color: Config.settingsBackground; border.color: (weatherWindUnitXExtraField.activeFocus || weatherWindUnitXExtraField.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 }
                        function applyValue(v){var n=Number(v);if(!isFinite(n))n=Config.weatherWindUnitX;n=Math.max(0,Math.min(300,Math.round(n)));Config.weatherWindUnitX=n;text=String(n);settings.save()}
                        onEditingFinished:applyValue(text);MouseArea{anchors.fill:parent;acceptedButtons:Qt.NoButton;onWheel:wheel=>{weatherWindUnitXExtraField.applyValue(Config.weatherWindUnitX+host.wheelDelta(wheel, 1));wheel.accepted=true}} Connections{target:Config;function onWeatherWindUnitXChanged(){weatherWindUnitXExtraField.text=String(Config.weatherWindUnitX)}}
                    }
                    SettingsTextField { id: weatherWindUnitYExtraField; width: 62; height: 30; text: String(Config.weatherWindUnitY); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; inputMethodHints: Qt.ImhNone; background: Rectangle { color: Config.settingsBackground; border.color: (weatherWindUnitYExtraField.activeFocus || weatherWindUnitYExtraField.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 }
                        function applyValue(v){var n=Number(v);if(!isFinite(n))n=Config.weatherWindUnitY;n=Math.max(-20,Math.min(80,Math.round(n)));Config.weatherWindUnitY=n;text=String(n);settings.save()}
                        onEditingFinished:applyValue(text);MouseArea{anchors.fill:parent;acceptedButtons:Qt.NoButton;onWheel:wheel=>{weatherWindUnitYExtraField.applyValue(Config.weatherWindUnitY+host.wheelDelta(wheel, 1));wheel.accepted=true}} Connections{target:Config;function onWeatherWindUnitYChanged(){weatherWindUnitYExtraField.text=String(Config.weatherWindUnitY)}}
                    }
                    SettingsTextField { id: weatherWindUnitWidthExtraField; width: 62; height: 30; text: String(Config.weatherWindUnitWidth); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; inputMethodHints: Qt.ImhDigitsOnly; background: Rectangle { color: Config.settingsBackground; border.color: (weatherWindUnitWidthExtraField.activeFocus || weatherWindUnitWidthExtraField.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 }
                        function applyValue(v){var n=Number(v);if(!isFinite(n))n=Config.weatherWindUnitWidth;n=Math.max(10,Math.min(120,Math.round(n)));Config.weatherWindUnitWidth=n;text=String(n);settings.save()}
                        onEditingFinished:applyValue(text);MouseArea{anchors.fill:parent;acceptedButtons:Qt.NoButton;onWheel:wheel=>{weatherWindUnitWidthExtraField.applyValue(Config.weatherWindUnitWidth+host.wheelDelta(wheel, 1));wheel.accepted=true}} Connections{target:Config;function onWeatherWindUnitWidthChanged(){weatherWindUnitWidthExtraField.text=String(Config.weatherWindUnitWidth)}}
                    }
                }
                Row { visible: host.currentOtherTab === 3 && host.currentOtherSubTab === 1; width: parent.width; height: 30; spacing: 8
                    Text { width: 210; text: "Давление: ширина / шрифт"; color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); verticalAlignment: Text.AlignVCenter }
                    SettingsTextField { id: weatherPressureWidthExtraField; width: 70; height: 30; text: String(Config.weatherPressureValueWidth); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; inputMethodHints: Qt.ImhDigitsOnly; background: Rectangle { color: Config.settingsBackground; border.color: (weatherPressureWidthExtraField.activeFocus || weatherPressureWidthExtraField.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 }
                        function applyValue(v){var n=Number(v);if(!isFinite(n))n=Config.weatherPressureValueWidth;n=Math.max(20,Math.min(180,Math.round(n)));Config.weatherPressureValueWidth=n;text=String(n);settings.save()}
                        onEditingFinished:applyValue(text);MouseArea{anchors.fill:parent;acceptedButtons:Qt.NoButton;onWheel:wheel=>{weatherPressureWidthExtraField.applyValue(Config.weatherPressureValueWidth+host.wheelDelta(wheel, 1));wheel.accepted=true}} Connections{target:Config;function onWeatherPressureValueWidthChanged(){weatherPressureWidthExtraField.text=String(Config.weatherPressureValueWidth)}}
                    }
                    SettingsTextField { id: weatherPressureFontExtraField; width: 70; height: 30; text: String(Config.weatherPressureFontSize); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; inputMethodHints: Qt.ImhDigitsOnly; background: Rectangle { color: Config.settingsBackground; border.color: (weatherPressureFontExtraField.activeFocus || weatherPressureFontExtraField.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 }
                        function applyValue(v){var n=Number(v);if(!isFinite(n))n=Config.weatherPressureFontSize;n=Math.max(8,Math.min(48,Math.round(n)));Config.weatherPressureFontSize=n;text=String(n);settings.save()}
                        onEditingFinished:applyValue(text);MouseArea{anchors.fill:parent;acceptedButtons:Qt.NoButton;onWheel:wheel=>{weatherPressureFontExtraField.applyValue(Config.weatherPressureFontSize+host.wheelDelta(wheel, 1));wheel.accepted=true}} Connections{target:Config;function onWeatherPressureFontSizeChanged(){weatherPressureFontExtraField.text=String(Config.weatherPressureFontSize)}}
                    }
                }
                Row { visible: host.currentOtherTab === 3 && host.currentOtherSubTab === 1; width: parent.width; height: 30; spacing: 8
                    Text { width: 210; text: "Ед. давления: X / Y / шрифт"; color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); verticalAlignment: Text.AlignVCenter }
                    SettingsTextField { id: weatherPressureUnitXExtraField; width: 60; height: 30; text: String(Config.weatherPressureUnitX); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(10); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; inputMethodHints: Qt.ImhDigitsOnly; background: Rectangle { color: Config.settingsBackground; border.color: (weatherPressureUnitXExtraField.activeFocus || weatherPressureUnitXExtraField.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 }
                        function applyValue(v){var n=Number(v);if(!isFinite(n))n=Config.weatherPressureUnitX;n=Math.max(0,Math.min(300,Math.round(n)));Config.weatherPressureUnitX=n;text=String(n);settings.save()}
                        onEditingFinished:applyValue(text);MouseArea{anchors.fill:parent;acceptedButtons:Qt.NoButton;onWheel:wheel=>{weatherPressureUnitXExtraField.applyValue(Config.weatherPressureUnitX+host.wheelDelta(wheel, 1));wheel.accepted=true}} Connections{target:Config;function onWeatherPressureUnitXChanged(){weatherPressureUnitXExtraField.text=String(Config.weatherPressureUnitX)}}
                    }
                    SettingsTextField { id: weatherPressureUnitYExtraField; width: 60; height: 30; text: String(Config.weatherPressureUnitY); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(10); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; inputMethodHints: Qt.ImhNone; background: Rectangle { color: Config.settingsBackground; border.color: (weatherPressureUnitYExtraField.activeFocus || weatherPressureUnitYExtraField.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 }
                        function applyValue(v){var n=Number(v);if(!isFinite(n))n=Config.weatherPressureUnitY;n=Math.max(-20,Math.min(80,Math.round(n)));Config.weatherPressureUnitY=n;text=String(n);settings.save()}
                        onEditingFinished:applyValue(text);MouseArea{anchors.fill:parent;acceptedButtons:Qt.NoButton;onWheel:wheel=>{weatherPressureUnitYExtraField.applyValue(Config.weatherPressureUnitY+host.wheelDelta(wheel, 1));wheel.accepted=true}} Connections{target:Config;function onWeatherPressureUnitYChanged(){weatherPressureUnitYExtraField.text=String(Config.weatherPressureUnitY)}}
                    }
                    SettingsTextField { id: weatherPressureUnitFontExtraField; width: 60; height: 30; text: String(Config.weatherPressureUnitFontSize); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(10); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; inputMethodHints: Qt.ImhDigitsOnly; background: Rectangle { color: Config.settingsBackground; border.color: (weatherPressureUnitFontExtraField.activeFocus || weatherPressureUnitFontExtraField.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 }
                        function applyValue(v){var n=Number(v);if(!isFinite(n))n=Config.weatherPressureUnitFontSize;n=Math.max(6,Math.min(30,Math.round(n)));Config.weatherPressureUnitFontSize=n;text=String(n);settings.save()}
                        onEditingFinished:applyValue(text);MouseArea{anchors.fill:parent;acceptedButtons:Qt.NoButton;onWheel:wheel=>{weatherPressureUnitFontExtraField.applyValue(Config.weatherPressureUnitFontSize+host.wheelDelta(wheel, 1));wheel.accepted=true}} Connections{target:Config;function onWeatherPressureUnitFontSizeChanged(){weatherPressureUnitFontExtraField.text=String(Config.weatherPressureUnitFontSize)}}
                    }
                }
                Text { visible: host.currentOtherTab === 3 && host.currentOtherSubTab === 2; text: "Почасовой блок"; color: Config.settingsSubheading; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(10) }
                Row { visible: host.currentOtherTab === 3 && host.currentOtherSubTab === 2; width: parent.width; height: 30; spacing: 8
                    Text { width: 210; text: "Количество часов"; color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); verticalAlignment: Text.AlignVCenter }
                    SettingsTextField { id: whCount; width: 58; height: 30; text: String(Config.weatherHourlyCount); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(10); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; background: Rectangle { color: Config.settingsBackground; border.color: (whCount.activeFocus || whCount.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 } function applyValue(v){var n=Number(v);if(!isFinite(n))n=Config.weatherHourlyCount;n=Math.max(1,Math.min(12,Math.round(n)));Config.weatherHourlyCount=n;text=String(n);settings.save()} onEditingFinished:applyValue(text); MouseArea { anchors.fill: parent; acceptedButtons: Qt.NoButton; onWheel: wheel => { whCount.applyValue(Number(whCount.text) + host.wheelDelta(wheel, 1)); wheel.accepted = true } } }
                }
                Row { visible: host.currentOtherTab === 3 && host.currentOtherSubTab === 2; width: parent.width; height: 30; spacing: 8
                    Text { width: 210; text: "Верхний отступ"; color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); verticalAlignment: Text.AlignVCenter }
                    SettingsTextField { id: whPad; width: 58; height: 30; text: String(Config.weatherHourlyTopPadding); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(10); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; background: Rectangle { color: Config.settingsBackground; border.color: (whPad.activeFocus || whPad.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 } function applyValue(v){var n=Number(v);if(!isFinite(n))n=Config.weatherHourlyTopPadding;n=Math.max(0,Math.min(40,Math.round(n)));Config.weatherHourlyTopPadding=n;text=String(n);settings.save()} onEditingFinished:applyValue(text); MouseArea { anchors.fill: parent; acceptedButtons: Qt.NoButton; onWheel: wheel => { whPad.applyValue(Number(whPad.text) + host.wheelDelta(wheel, 1)); wheel.accepted = true } } }
                }
                Row { visible: host.currentOtherTab === 3 && host.currentOtherSubTab === 2; width: parent.width; height: 24; spacing: 8
                    Item { width: 210; height: 24 }
                    Text { width: 58; y: 4; text: "Y"; color: Config.textMuted; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(10); horizontalAlignment: Text.AlignHCenter; verticalAlignment: Text.AlignVCenter }
                    Text { width: 58; y: 4; text: "Размер"; color: Config.textMuted; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(10); horizontalAlignment: Text.AlignHCenter; verticalAlignment: Text.AlignVCenter }
                }
                Row { visible: host.currentOtherTab === 3 && host.currentOtherSubTab === 2; width: parent.width; height: 30; spacing: 8
                    Text { width: 210; text: "Время"; color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); verticalAlignment: Text.AlignVCenter }
                    SettingsTextField { id: whDayYTable; width: 58; height: 30; text: String(Config.weatherHourlyDayY); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(10); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; background: Rectangle { color: Config.settingsBackground; border.color: (whDayYTable.activeFocus || whDayYTable.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 } function applyValue(v){var n=Number(v);if(!isFinite(n))n=Config.weatherHourlyDayY;n=Math.max(0,Math.min(120,Math.round(n)));Config.weatherHourlyDayY=n;text=String(n);settings.save()} onEditingFinished:applyValue(text); MouseArea { anchors.fill: parent; acceptedButtons: Qt.NoButton; onWheel: wheel => { whDayYTable.applyValue(Number(whDayYTable.text) + host.wheelDelta(wheel, 1)); wheel.accepted = true } } }
                    SettingsTextField { id: whDaySizeTable; width: 58; height: 30; text: String(Config.weatherHourlyDayFontSize); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(10); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; background: Rectangle { color: Config.settingsBackground; border.color: (whDaySizeTable.activeFocus || whDaySizeTable.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 } function applyValue(v){var n=Number(v);if(!isFinite(n))n=Config.weatherHourlyDayFontSize;n=Math.max(6,Math.min(32,Math.round(n)));Config.weatherHourlyDayFontSize=n;text=String(n);settings.save()} onEditingFinished:applyValue(text); MouseArea { anchors.fill: parent; acceptedButtons: Qt.NoButton; onWheel: wheel => { whDaySizeTable.applyValue(Number(whDaySizeTable.text) + host.wheelDelta(wheel, 1)); wheel.accepted = true } } }
                }
                Row { visible: host.currentOtherTab === 3 && host.currentOtherSubTab === 2; width: parent.width; height: 30; spacing: 8
                    Text { width: 210; text: "Иконка"; color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); verticalAlignment: Text.AlignVCenter }
                    SettingsTextField { id: whIconYTable; width: 58; height: 30; text: String(Config.weatherHourlyIconY); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(10); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; background: Rectangle { color: Config.settingsBackground; border.color: (whIconYTable.activeFocus || whIconYTable.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 } function applyValue(v){var n=Number(v);if(!isFinite(n))n=Config.weatherHourlyIconY;n=Math.max(0,Math.min(120,Math.round(n)));Config.weatherHourlyIconY=n;text=String(n);settings.save()} onEditingFinished:applyValue(text); MouseArea { anchors.fill: parent; acceptedButtons: Qt.NoButton; onWheel: wheel => { whIconYTable.applyValue(Number(whIconYTable.text) + host.wheelDelta(wheel, 1)); wheel.accepted = true } } }
                    SettingsTextField { id: whIconSizeTable; width: 58; height: 30; text: String(Config.weatherHourlyIconWidth); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(10); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; background: Rectangle { color: Config.settingsBackground; border.color: (whIconSizeTable.activeFocus || whIconSizeTable.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 } function applyValue(v){var n=Number(v);if(!isFinite(n))n=Config.weatherHourlyIconWidth;n=Math.max(16,Math.min(90,Math.round(n)));Config.weatherHourlyIconWidth=n;text=String(n);settings.save()} onEditingFinished:applyValue(text); MouseArea { anchors.fill: parent; acceptedButtons: Qt.NoButton; onWheel: wheel => { whIconSizeTable.applyValue(Number(whIconSizeTable.text) + host.wheelDelta(wheel, 1)); wheel.accepted = true } } }
                }
                Row { visible: host.currentOtherTab === 3 && host.currentOtherSubTab === 2; width: parent.width; height: 30; spacing: 8
                    Text { width: 210; text: "Температура"; color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); verticalAlignment: Text.AlignVCenter }
                    SettingsTextField { id: whTempYTable; width: 58; height: 30; text: String(Config.weatherHourlyTempY); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(10); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; background: Rectangle { color: Config.settingsBackground; border.color: (whTempYTable.activeFocus || whTempYTable.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 } function applyValue(v){var n=Number(v);if(!isFinite(n))n=Config.weatherHourlyTempY;n=Math.max(0,Math.min(150,Math.round(n)));Config.weatherHourlyTempY=n;text=String(n);settings.save()} onEditingFinished:applyValue(text); MouseArea { anchors.fill: parent; acceptedButtons: Qt.NoButton; onWheel: wheel => { whTempYTable.applyValue(Number(whTempYTable.text) + host.wheelDelta(wheel, 1)); wheel.accepted = true } } }
                    SettingsTextField { id: whTempSizeTable; width: 58; height: 30; text: String(Config.weatherHourlyTempFontSize); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(10); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; background: Rectangle { color: Config.settingsBackground; border.color: (whTempSizeTable.activeFocus || whTempSizeTable.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 } function applyValue(v){var n=Number(v);if(!isFinite(n))n=Config.weatherHourlyTempFontSize;n=Math.max(6,Math.min(32,Math.round(n)));Config.weatherHourlyTempFontSize=n;text=String(n);settings.save()} onEditingFinished:applyValue(text); MouseArea { anchors.fill: parent; acceptedButtons: Qt.NoButton; onWheel: wheel => { whTempSizeTable.applyValue(Number(whTempSizeTable.text) + host.wheelDelta(wheel, 1)); wheel.accepted = true } } }
                }
                Text { visible: host.currentOtherTab === 3 && host.currentOtherSubTab === 3; text: "Дневной блок — максимум 4 колонки"; color: Config.settingsSubheading; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(10) }
                Row { visible: host.currentOtherTab === 3 && host.currentOtherSubTab === 3; width: parent.width; height: 30; spacing: 8
                    Text { width: 210; text: "Количество дней"; color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); verticalAlignment: Text.AlignVCenter }
                    SettingsTextField { id: wdCount; width: 58; height: 30; text: String(Config.weatherDailyCount); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(10); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; background: Rectangle { color: Config.settingsBackground; border.color: (wdCount.activeFocus || wdCount.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 } function applyValue(v){var n=Number(v);if(!isFinite(n))n=Config.weatherDailyCount;n=Math.max(1,Math.min(4,Math.round(n)));Config.weatherDailyCount=n;text=String(n);settings.save()} onEditingFinished:applyValue(text); MouseArea { anchors.fill: parent; acceptedButtons: Qt.NoButton; onWheel: wheel => { wdCount.applyValue(Number(wdCount.text) + host.wheelDelta(wheel, 1)); wheel.accepted = true } } }
                }
                Row { visible: host.currentOtherTab === 3 && host.currentOtherSubTab === 3; width: parent.width; height: 30; spacing: 8
                    Text { width: 210; text: "Верхний отступ"; color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); verticalAlignment: Text.AlignVCenter }
                    SettingsTextField { id: wdPad; width: 58; height: 30; text: String(Config.weatherDailyTopPadding); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(10); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; background: Rectangle { color: Config.settingsBackground; border.color: (wdPad.activeFocus || wdPad.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 } function applyValue(v){var n=Number(v);if(!isFinite(n))n=Config.weatherDailyTopPadding;n=Math.max(0,Math.min(40,Math.round(n)));Config.weatherDailyTopPadding=n;text=String(n);settings.save()} onEditingFinished:applyValue(text); MouseArea { anchors.fill: parent; acceptedButtons: Qt.NoButton; onWheel: wheel => { wdPad.applyValue(Number(wdPad.text) + host.wheelDelta(wheel, 1)); wheel.accepted = true } } }
                }
                Row { visible: host.currentOtherTab === 3 && host.currentOtherSubTab === 3; width: parent.width; height: 24; spacing: 8
                    Item { width: 210; height: 24 }
                    Text { width: 58; y: 4; text: "Y"; color: Config.textMuted; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(10); horizontalAlignment: Text.AlignHCenter; verticalAlignment: Text.AlignVCenter }
                    Text { width: 58; y: 4; text: "Размер"; color: Config.textMuted; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(10); horizontalAlignment: Text.AlignHCenter; verticalAlignment: Text.AlignVCenter }
                }
                Row { visible: host.currentOtherTab === 3 && host.currentOtherSubTab === 3; width: parent.width; height: 30; spacing: 8
                    Text { width: 210; text: "День"; color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); verticalAlignment: Text.AlignVCenter }
                    SettingsTextField { id: wdDayYTable; width: 58; height: 30; text: String(Config.weatherDailyDayY); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(10); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; background: Rectangle { color: Config.settingsBackground; border.color: (wdDayYTable.activeFocus || wdDayYTable.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 } function applyValue(v){var n=Number(v);if(!isFinite(n))n=Config.weatherDailyDayY;n=Math.max(0,Math.min(120,Math.round(n)));Config.weatherDailyDayY=n;text=String(n);settings.save()} onEditingFinished:applyValue(text); MouseArea { anchors.fill: parent; acceptedButtons: Qt.NoButton; onWheel: wheel => { wdDayYTable.applyValue(Number(wdDayYTable.text) + host.wheelDelta(wheel, 1)); wheel.accepted = true } } }
                    SettingsTextField { id: wdDaySizeTable; width: 58; height: 30; text: String(Config.weatherDailyDayFontSize); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(10); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; background: Rectangle { color: Config.settingsBackground; border.color: (wdDaySizeTable.activeFocus || wdDaySizeTable.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 } function applyValue(v){var n=Number(v);if(!isFinite(n))n=Config.weatherDailyDayFontSize;n=Math.max(6,Math.min(32,Math.round(n)));Config.weatherDailyDayFontSize=n;text=String(n);settings.save()} onEditingFinished:applyValue(text); MouseArea { anchors.fill: parent; acceptedButtons: Qt.NoButton; onWheel: wheel => { wdDaySizeTable.applyValue(Number(wdDaySizeTable.text) + host.wheelDelta(wheel, 1)); wheel.accepted = true } } }
                }
                Row { visible: host.currentOtherTab === 3 && host.currentOtherSubTab === 3; width: parent.width; height: 30; spacing: 8
                    Text { width: 210; text: "Иконка"; color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); verticalAlignment: Text.AlignVCenter }
                    SettingsTextField { id: wdIconYTable; width: 58; height: 30; text: String(Config.weatherDailyIconY); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(10); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; background: Rectangle { color: Config.settingsBackground; border.color: (wdIconYTable.activeFocus || wdIconYTable.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 } function applyValue(v){var n=Number(v);if(!isFinite(n))n=Config.weatherDailyIconY;n=Math.max(0,Math.min(120,Math.round(n)));Config.weatherDailyIconY=n;text=String(n);settings.save()} onEditingFinished:applyValue(text); MouseArea { anchors.fill: parent; acceptedButtons: Qt.NoButton; onWheel: wheel => { wdIconYTable.applyValue(Number(wdIconYTable.text) + host.wheelDelta(wheel, 1)); wheel.accepted = true } } }
                    SettingsTextField { id: wdIconSizeTable; width: 58; height: 30; text: String(Config.weatherDailyIconWidth); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(10); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; background: Rectangle { color: Config.settingsBackground; border.color: (wdIconSizeTable.activeFocus || wdIconSizeTable.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 } function applyValue(v){var n=Number(v);if(!isFinite(n))n=Config.weatherDailyIconWidth;n=Math.max(16,Math.min(90,Math.round(n)));Config.weatherDailyIconWidth=n;text=String(n);settings.save()} onEditingFinished:applyValue(text); MouseArea { anchors.fill: parent; acceptedButtons: Qt.NoButton; onWheel: wheel => { wdIconSizeTable.applyValue(Number(wdIconSizeTable.text) + host.wheelDelta(wheel, 1)); wheel.accepted = true } } }
                }
                Row { visible: host.currentOtherTab === 3 && host.currentOtherSubTab === 3; width: parent.width; height: 24; spacing: 8
                    Item { width: 210; height: 24 }
                    Text { width: 58; y: 4; text: "X"; color: Config.textMuted; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(10); horizontalAlignment: Text.AlignHCenter; verticalAlignment: Text.AlignVCenter }
                    Text { width: 58; y: 4; text: "Y"; color: Config.textMuted; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(10); horizontalAlignment: Text.AlignHCenter; verticalAlignment: Text.AlignVCenter }
                    Text { width: 58; y: 4; text: "Шрифт"; color: Config.textMuted; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(10); horizontalAlignment: Text.AlignHCenter; verticalAlignment: Text.AlignVCenter }
                }
                Row { visible: host.currentOtherTab === 3 && host.currentOtherSubTab === 3; width: parent.width; height: 30; spacing: 8
                    Text { width: 210; text: "Дневная температура"; color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); verticalAlignment: Text.AlignVCenter }
                    SettingsTextField { id: wdHX; width: 58; height: 30; text: String(Config.weatherDailyHighTempX); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(10); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; background: Rectangle { color: Config.settingsBackground; border.color: (wdHX.activeFocus || wdHX.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 } function applyValue(v){var n=Number(v);if(!isFinite(n))n=Config.weatherDailyHighTempX;n=Math.max(-100,Math.min(100,Math.round(n)));Config.weatherDailyHighTempX=n;text=String(n);settings.save()} onEditingFinished:applyValue(text); MouseArea { anchors.fill: parent; acceptedButtons: Qt.NoButton; onWheel: wheel => { wdHX.applyValue(Number(wdHX.text) + host.wheelDelta(wheel, 1)); wheel.accepted = true } } }
                    SettingsTextField { id: wdHY; width: 58; height: 30; text: String(Config.weatherDailyHighTempY); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(10); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; background: Rectangle { color: Config.settingsBackground; border.color: (wdHY.activeFocus || wdHY.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 } function applyValue(v){var n=Number(v);if(!isFinite(n))n=Config.weatherDailyHighTempY;n=Math.max(0,Math.min(150,Math.round(n)));Config.weatherDailyHighTempY=n;text=String(n);settings.save()} onEditingFinished:applyValue(text); MouseArea { anchors.fill: parent; acceptedButtons: Qt.NoButton; onWheel: wheel => { wdHY.applyValue(Number(wdHY.text) + host.wheelDelta(wheel, 1)); wheel.accepted = true } } }
                    SettingsTextField { id: wdHF; width: 58; height: 30; text: String(Config.weatherDailyHighTempFontSize); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(10); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; background: Rectangle { color: Config.settingsBackground; border.color: (wdHF.activeFocus || wdHF.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 } function applyValue(v){var n=Number(v);if(!isFinite(n))n=Config.weatherDailyHighTempFontSize;n=Math.max(6,Math.min(32,Math.round(n)));Config.weatherDailyHighTempFontSize=n;text=String(n);settings.save()} onEditingFinished:applyValue(text); MouseArea { anchors.fill: parent; acceptedButtons: Qt.NoButton; onWheel: wheel => { wdHF.applyValue(Number(wdHF.text) + host.wheelDelta(wheel, 1)); wheel.accepted = true } } }
                }
                Row { visible: host.currentOtherTab === 3 && host.currentOtherSubTab === 3; width: parent.width; height: 30; spacing: 8
                    Text { width: 210; text: "Ночная температура"; color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(11); verticalAlignment: Text.AlignVCenter }
                    SettingsTextField { id: wdLX; width: 58; height: 30; text: String(Config.weatherDailyLowTempX); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(10); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; background: Rectangle { color: Config.settingsBackground; border.color: (wdLX.activeFocus || wdLX.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 } function applyValue(v){var n=Number(v);if(!isFinite(n))n=Config.weatherDailyLowTempX;n=Math.max(-100,Math.min(100,Math.round(n)));Config.weatherDailyLowTempX=n;text=String(n);settings.save()} onEditingFinished:applyValue(text); MouseArea { anchors.fill: parent; acceptedButtons: Qt.NoButton; onWheel: wheel => { wdLX.applyValue(Number(wdLX.text) + host.wheelDelta(wheel, 1)); wheel.accepted = true } } }
                    SettingsTextField { id: wdLY; width: 58; height: 30; text: String(Config.weatherDailyLowTempY); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(10); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; background: Rectangle { color: Config.settingsBackground; border.color: (wdLY.activeFocus || wdLY.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 } function applyValue(v){var n=Number(v);if(!isFinite(n))n=Config.weatherDailyLowTempY;n=Math.max(0,Math.min(180,Math.round(n)));Config.weatherDailyLowTempY=n;text=String(n);settings.save()} onEditingFinished:applyValue(text); MouseArea { anchors.fill: parent; acceptedButtons: Qt.NoButton; onWheel: wheel => { wdLY.applyValue(Number(wdLY.text) + host.wheelDelta(wheel, 1)); wheel.accepted = true } } }
                    SettingsTextField { id: wdLF; width: 58; height: 30; text: String(Config.weatherDailyLowTempFontSize); color: Config.text; font.family: Config.settingsFont; font.pixelSize: Config.settingsUiSize(10); horizontalAlignment: Text.AlignHCenter; activeFocusOnTab: true; background: Rectangle { color: Config.settingsBackground; border.color: (wdLF.activeFocus || wdLF.pointerHovered) ? Config.accent : Config.baseColor; border.width: 1; radius: 4 } function applyValue(v){var n=Number(v);if(!isFinite(n))n=Config.weatherDailyLowTempFontSize;n=Math.max(6,Math.min(32,Math.round(n)));Config.weatherDailyLowTempFontSize=n;text=String(n);settings.save()} onEditingFinished:applyValue(text); MouseArea { anchors.fill: parent; acceptedButtons: Qt.NoButton; onWheel: wheel => { wdLF.applyValue(Number(wdLF.text) + host.wheelDelta(wheel, 1)); wheel.accepted = true } } }
                }
}
