#!/bin/bash
source "$(dirname "$0")/env"

declare -r IMG_PATH="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}/desktop-shell-player"
declare -r TIMER_DIR="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}/timer"

# Создание всех необходимых директорий при старте оболочки
[[ ! -d "$IMG_PATH" ]] && mkdir -p "$IMG_PATH"
[[ ! -d "$TIMER_DIR" ]] && mkdir -p "$TIMER_DIR"

echo "ok"