#!/bin/bash
source "$(dirname "$0")/env"
source "$(dirname "$0")/timer.d/common.sh"
source "$(dirname "$0")/timer.d/actions.sh"
source "$(dirname "$0")/timer.d/daemon.sh"

case "$1" in
    add)           timer_add "$2" "$3";;
    add_at)        timer_add_at "$2";;
    up)            timer_up "$2";;
    down)          timer_down "$2";;
    delete)        timer_delete "$2";;
    update_color)  update_color "$2";;
    set_comment)   set_comment "$2" "$3";;
    refresh)       refresh "$2";;
    refresh_add)   refresh_add "$2";;
    toggle_pause)  toggle_pause "$2";;
    *)             run_daemon;;
esac
